### ISSUE TITLE
Who is chocolatebrownie?

### ISSUE THREAD

**Issue by iev6** [iitmcvg/Content#1]
Is this his real life?
Is this just confectionery?
Caught in a sugar slide,
No escape from reality.

Open your eyes
Look up to the repo and see
He's just a black dough, he needs no sympathy

Because he's easy code and easy goal
Little right and little low

Any way the boy's codes doesn't really matter to me, to me.

**Comment by awearytraveler** [comment]
I actually thought someone found an issue in our repo.. :P

**Comment by varun19299** [comment]
Identity  sorted so ...

**Comment by iev6** [comment]
Paaah how to close issues like
