### ISSUE TITLE
Unable to download iitmcvg software

### ISSUE THREAD

**Issue by KarilGarg** [iitmcvg/Content#18]
My OS is windows, i have tried 5-6 times at least downloading that, but it slows down after some time ( speed is in bits). So what to do to complete the download.
Thanks

**Comment by varun19299** [comment]
Is the issue with downloading docker tools or the running this command

```
docker run -it -p 8888:8888 --name cvi iitmcvg/session:intro_CV bash
```

**Comment by KarilGarg** [comment]
okay. thanks its sorted. btw can u please tell where to solve the problems given in jupyter notebooks or docker.

**Comment by varun19299** [comment]
You can solve it using jupyter, which is available on the container

**Comment by KarilGarg** [comment]
Hello.
I downloaded docker and it has been successfully downloaded. Sorry that i
didn't inform you about that.
That said, can you please tell me, how should I proceed now. By this i mean
how to slove the given problems and what else i can do besides these
problems.
Thanks

**Comment by varun19299** [comment]
You could meet us in person at CFI to discuss this.
